from lk_metro.ParallelGeographicDiagram.ParallelGeographicDiagramLabelInterchangeCandidatesMixin import \
    ParallelGeographicDiagramLabelInterchangeCandidatesMixin
from lk_metro.ParallelGeographicDiagram.ParallelGeographicDiagramLabelInterchangePlacementMixin import \
    ParallelGeographicDiagramLabelInterchangePlacementMixin


class ParallelGeographicDiagramLabelInterchangeMixin(
    ParallelGeographicDiagramLabelInterchangePlacementMixin,
    ParallelGeographicDiagramLabelInterchangeCandidatesMixin,
):
    pass
