from lk_metro.ParallelGeographicDiagram.ParallelGeographicDiagramLabelStationCandidatesMixin import \
    ParallelGeographicDiagramLabelStationCandidatesMixin
from lk_metro.ParallelGeographicDiagram.ParallelGeographicDiagramLabelStationPlacementMixin import \
    ParallelGeographicDiagramLabelStationPlacementMixin


class ParallelGeographicDiagramLabelStationMixin(
    ParallelGeographicDiagramLabelStationPlacementMixin,
    ParallelGeographicDiagramLabelStationCandidatesMixin,
):
    pass
