from lk_metro.GeographicDiagram.GeographicDiagram import GeographicDiagram
from lk_metro.ParallelGeographicDiagram.ParallelGeographicDiagramCoreMixin import \
    ParallelGeographicDiagramCoreMixin
from lk_metro.ParallelGeographicDiagram.ParallelGeographicDiagramLabelBoundsMixin import \
    ParallelGeographicDiagramLabelBoundsMixin
from lk_metro.ParallelGeographicDiagram.ParallelGeographicDiagramLabelInterchangeCandidatesMixin import \
    ParallelGeographicDiagramLabelInterchangeCandidatesMixin
from lk_metro.ParallelGeographicDiagram.ParallelGeographicDiagramLabelInterchangePlacementMixin import \
    ParallelGeographicDiagramLabelInterchangePlacementMixin
from lk_metro.ParallelGeographicDiagram.ParallelGeographicDiagramLabelOptionMixin import \
    ParallelGeographicDiagramLabelOptionMixin
from lk_metro.ParallelGeographicDiagram.ParallelGeographicDiagramLabelPayloadMixin import \
    ParallelGeographicDiagramLabelPayloadMixin
from lk_metro.ParallelGeographicDiagram.ParallelGeographicDiagramLabelRefineFlowMixin import \
    ParallelGeographicDiagramLabelRefineFlowMixin
from lk_metro.ParallelGeographicDiagram.ParallelGeographicDiagramLabelStationCandidatesMixin import \
    ParallelGeographicDiagramLabelStationCandidatesMixin
from lk_metro.ParallelGeographicDiagram.ParallelGeographicDiagramLabelStationPlacementMixin import \
    ParallelGeographicDiagramLabelStationPlacementMixin
from lk_metro.ParallelGeographicDiagram.ParallelGeographicDiagramLabelTextMixin import \
    ParallelGeographicDiagramLabelTextMixin
from lk_metro.ParallelGeographicDiagram.ParallelGeographicDiagramPathMixin import \
    ParallelGeographicDiagramPathMixin
from lk_metro.ParallelGeographicDiagram.ParallelGeographicDiagramRouteBuildMixin import \
    ParallelGeographicDiagramRouteBuildMixin
from lk_metro.ParallelGeographicDiagram.ParallelGeographicDiagramRouteGeometryMixin import \
    ParallelGeographicDiagramRouteGeometryMixin
from lk_metro.ParallelGeographicDiagram.ParallelGeographicDiagramStationSvgMixin import \
    ParallelGeographicDiagramStationSvgMixin
from lk_metro.ParallelGeographicDiagram.ParallelGeographicDiagramStyleMixin import \
    ParallelGeographicDiagramStyleMixin
from lk_metro.ParallelGeographicDiagram.ParallelGeographicDiagramSvgMarkupMixin import \
    ParallelGeographicDiagramSvgMarkupMixin
from lk_metro.ParallelGeographicDiagram.ParallelGeographicDiagramTickGeometryMixin import \
    ParallelGeographicDiagramTickGeometryMixin
from lk_metro.ParallelGeographicDiagram.ParallelGeographicDiagramTickPlacementMixin import \
    ParallelGeographicDiagramTickPlacementMixin


class ParallelGeographicDiagram(
    ParallelGeographicDiagramStyleMixin,
    ParallelGeographicDiagramCoreMixin,
    ParallelGeographicDiagramSvgMarkupMixin,
    ParallelGeographicDiagramStationSvgMixin,
    ParallelGeographicDiagramLabelTextMixin,
    ParallelGeographicDiagramPathMixin,
    ParallelGeographicDiagramRouteBuildMixin,
    ParallelGeographicDiagramRouteGeometryMixin,
    ParallelGeographicDiagramTickPlacementMixin,
    ParallelGeographicDiagramTickGeometryMixin,
    ParallelGeographicDiagramLabelInterchangePlacementMixin,
    ParallelGeographicDiagramLabelInterchangeCandidatesMixin,
    ParallelGeographicDiagramLabelStationPlacementMixin,
    ParallelGeographicDiagramLabelStationCandidatesMixin,
    ParallelGeographicDiagramLabelPayloadMixin,
    ParallelGeographicDiagramLabelOptionMixin,
    ParallelGeographicDiagramLabelRefineFlowMixin,
    ParallelGeographicDiagramLabelBoundsMixin,
    GeographicDiagram,
):
    pass
